--PLAYER 테이블에서 팀별 최대 몸무게인 선수의
--TEAM_ID, REGION_NAME,PLAYER_NAME,WEIGHT 검색(WHERE IN 사용하기)
SELECT P.TEAM_ID,T.REGION_NAME,P.PLAYER_NAME,P.WEIGHT
FROM PLAYER P JOIN TEAM T
ON P.TEAM_ID=T.TEAM_ID
WHERE (P.TEAM_ID,WEIGHT) IN(SELECT TEAM_ID,MAX(WEIGHT) FROM PLAYER GROUP BY TEAM_ID);
--차이점알기
--PLAYER WEIGHT가 오른쪽 항의(MAX(WEIGHT)의 나열된 값중 하나라도 같은것이있으면 출력됨
--반대로 위의 쿼리문은 TEAM_ID와 WEIGHT모두가 같아야 출력됨
SELECT P.TEAM_ID,T.REGION_NAME,P.PLAYER_NAME,P.WEIGHT
FROM PLAYER P JOIN TEAM T
ON P.TEAM_ID=T.TEAM_ID
WHERE (WEIGHT) IN(SELECT MAX(WEIGHT) FROM PLAYER GROUP BY TEAM_ID);

--EMP테이블의 SAL을 DEPT테이블의 LOC별 평균 급여를 반올림한 값과
--각 LOC별 SAL 총 합을 검색하기
SELECT D.LOC,ROUND(AVG(SAL)),ROUND(SUM(SAL))
FROM EMP E JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
GROUP BY D.LOC;

--EMP 테이블에서 HIREDATE가 FORD의 입사년도와 같은 사원 전체 정보 검색
--DATE형식->VARCHAR2형식으로 변경할때 형식('YYYY-MM-DD')을 TO_CHAR의 인자로 전달해줘야함
SELECT *
FROM EMP
WHERE SUBSTR(TO_CHAR(HIREDATE,'YYYY-MM-DD'),1,4)=
(SELECT SUBSTR(TO_CHAR(HIREDATE,'YYYY-MM-DD'),1,4) FROM EMP WHERE ENAME='FORD');
--LIKE:포함된 문자열을 찾음
SELECT * FROM EMP
WHERE TO_CHAR(HIREDATE,'YYYY-MM-DD') LIKE(
(SELECT SUBSTR(TO_CHAR(HIREDATE,'YYYY-MM-DD'),1,4) FROM EMP WHERE ENAME='FORD')||'%');

--DATE형식->VARCHAR2형식으로 변경할때 형식('YYYY-MM-DD')을 TO_CHAR의 인자로 전달해줘야함
SELECT TO_CHAR(HIREDATE) FROM EMP;
SELECT TO_CHAR(HIREDATE,'YYYY-MM-DD') FROM EMP;

--JOBS 테이블에서 JOB_TITLE별 사원들 평균 급여 검색
--순서: FROM->WHERE->GROUP BY->HAVING->SELECT->ORDER BY
SELECT J.JOB_TITLE,AVG(E.SALARY)
FROM JOBS J JOIN EMPLOYEES E
ON  J.JOB_ID=E.JOB_ID
GROUP BY JOB_TITLE;

--AVG 함수를 쓰지 않고 PLAYER 테이블에서 선수들 평균 키 구하기(NULL 미포함)
SELECT ROUND((SUM(HEIGHT)/COUNT(HEIGHT))) AS "평균키"
FROM PLAYER;